// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentEvalSentiment.DB.Context;

#nullable disable

namespace StudentEvalSentiment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Academic.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Academic.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Academic.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("SectionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("SectionId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TermId");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Academic.Term", b =>
                {
                    b.Property<int>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("TermId");

                    b.ToTable("Term");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Evaluations.EvaluationSubmission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalKey")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsMobile")
                        .HasColumnType("bit");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SurveyId");

                    b.ToTable("EvaluationSubmissions");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Evaluations.EvaluationTarget", b =>
                {
                    b.Property<Guid>("TargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TargetOrder")
                        .HasColumnType("int");

                    b.Property<byte>("TargetType")
                        .HasColumnType("tinyint");

                    b.HasKey("TargetId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("SubmissionId", "TargetType", "TargetOrder")
                        .IsUnique();

                    b.ToTable("EvaluationTargets");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Evaluations.ImportBatch", b =>
                {
                    b.Property<Guid>("ImportBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowCountImported")
                        .HasColumnType("int");

                    b.Property<int>("RowCountTotal")
                        .HasColumnType("int");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImportBatchId");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Evaluations.LikertResponse", b =>
                {
                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte?>("Value")
                        .HasColumnType("tinyint");

                    b.HasKey("TargetId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("LikertResponses");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Evaluations.TextResponse", b =>
                {
                    b.Property<long>("TextResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TextResponseId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("RawText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TextResponseId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TargetId");

                    b.ToTable("TextResponses");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Survey.Survey", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyId"));

                    b.Property<DateTime?>("DateClose")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SurveyId");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Survey.SurveyQuestion", b =>
                {
                    b.Property<int>("SurveyQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyQuestionId"));

                    b.Property<string>("CanonicalText")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("ResponseType")
                        .HasColumnType("tinyint");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<byte>("TargetType")
                        .HasColumnType("tinyint");

                    b.HasKey("SurveyQuestionId");

                    b.HasIndex("SurveyId", "QuestionKey")
                        .IsUnique();

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Survey.SurveyQuestionHeader", b =>
                {
                    b.Property<int>("SurveyQuestionHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyQuestionHeaderId"));

                    b.Property<string>("HeaderText")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetOrder")
                        .HasColumnType("int");

                    b.Property<byte>("TargetType")
                        .HasColumnType("tinyint");

                    b.HasKey("SurveyQuestionHeaderId");

                    b.HasIndex("SurveyQuestionId");

                    b.HasIndex("SurveyId", "HeaderText")
                        .IsUnique();

                    b.ToTable("SurveyQuestionHeaders");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Academic.Section", b =>
                {
                    b.HasOne("StudentEvalSentiment.Models.Entities.Academic.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentEvalSentiment.Models.Entities.Academic.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Evaluations.EvaluationSubmission", b =>
                {
                    b.HasOne("StudentEvalSentiment.Models.Entities.Evaluations.ImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId");

                    b.HasOne("StudentEvalSentiment.Models.Entities.Academic.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentEvalSentiment.Models.Entities.Survey.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");

                    b.Navigation("Section");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Evaluations.EvaluationTarget", b =>
                {
                    b.HasOne("StudentEvalSentiment.Models.Entities.Academic.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.HasOne("StudentEvalSentiment.Models.Entities.Evaluations.EvaluationSubmission", "Submission")
                        .WithMany("Targets")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Evaluations.LikertResponse", b =>
                {
                    b.HasOne("StudentEvalSentiment.Models.Entities.Survey.SurveyQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentEvalSentiment.Models.Entities.Evaluations.EvaluationTarget", "Target")
                        .WithMany("LikertResponses")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Evaluations.TextResponse", b =>
                {
                    b.HasOne("StudentEvalSentiment.Models.Entities.Survey.SurveyQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentEvalSentiment.Models.Entities.Evaluations.EvaluationTarget", "Target")
                        .WithMany("TextResponses")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Survey.SurveyQuestion", b =>
                {
                    b.HasOne("StudentEvalSentiment.Models.Entities.Survey.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Survey.SurveyQuestionHeader", b =>
                {
                    b.HasOne("StudentEvalSentiment.Models.Entities.Survey.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentEvalSentiment.Models.Entities.Survey.SurveyQuestion", "SurveyQuestion")
                        .WithMany()
                        .HasForeignKey("SurveyQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");

                    b.Navigation("SurveyQuestion");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Evaluations.EvaluationSubmission", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("StudentEvalSentiment.Models.Entities.Evaluations.EvaluationTarget", b =>
                {
                    b.Navigation("LikertResponses");

                    b.Navigation("TextResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
